name: React App Boiler-plate
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      #Install Packages
      - name: Install Packages
        working-directory: nexus-informational
        run: npm install
      # Build the React app
      - name: Build
        working-directory: nexus-informational
        run: npm run build
      # Run Tests
      - name: Run Tests
        working-directory: nexus-informational
        run: npm test